apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc 
  labels:
    app: myapp-rc 
    type: front-end-rc 
spec:
  replicas: 2
  selector:
    type: front-end-rc 
  template:
    metadata:
      name: myapp-rc 
      labels:
        app: myapp-rc 
        type: front-end-rc 
    spec:
      containers:
        - name: nginx-rc 
          image: nginx
